### ISSUE TITLE
使用helm安装后metanode无法启动

### ISSUE THREAD

**Issue by cycwll** [cubefs/cubefs-helm#11]
使用helm安装后metanode无法启动
#values.yml中关于metanode的配置
```
metanode:
  labels:
    node_selector_key: chubaofs-metanode
    node_selector_value: enabled
  log_level: error
  total_mem: "26843545600"
  port: 17210
  prof: 17220
  raft_heartbeat: 17230
  raft_replica: 17240
  exporter_port: 9510
  resources:
    enabled: true
    requests:
      memory: "4Gi"
      cpu: "2000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"
```

#kubectl -n chubaofs get pods 
![image](https://user-images.githubusercontent.com/6410130/127819490-dae6db4d-5e13-4485-b550-25970f813c25.png)

#kubectl -n chubaofs describe po metanode-gtwgk
![image](https://user-images.githubusercontent.com/6410130/127819575-dd2d8168-b04c-4eb5-a6b7-f80f5f42d825.png)

#kubectl -n chubaofs logs metanode-gtwgk
![image](https://user-images.githubusercontent.com/6410130/127819705-5d7c2115-ca52-43b1-9392-aa32efb07846.png)
